### ISSUE TITLE
r-script/ jsonlite issue

### ISSUE THREAD

**Issue by deanbittner** [CMPUT401Group/analytic-engine#1]
I am getting an error when running the npm test target as below.  I see Matt has reported this issue to the r-script project without any noted resolution.

dean@STB-SIM2:~/analytic-engine$ npm test

> runwithit-it-analytic-engine@0.0.1 test /home/dean/analytic-engine
> babel-node spec/run.js

Started
.........undefined:1
installing packages:njsonlite
^

SyntaxError: Unexpected token i
    at Object.parse (native)
    at Socket.<anonymous> (/home/dean/analytic-engine/node_modules/r-script/index.js:34:25)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:537:20)
npm ERR! Test failed.  See above for more details.

**Comment by deanbittner** [comment]
With R installed globally and node installed as user with nvm, make sure that user is part of 'staff' (on Ubuntu), and as root, run R and ->
install.packages('jsonlite', dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages('outliers', dependencies=TRUE, repos='http://cran.rstudio.com/')

There is also an attachment replacement to 'analytic-engine/node_modules/r-script/index.js'.
[index.js.zip](https://github.com/CMPUT401Group/analytic-engine/files/646346/index.js.zip)

npm test at the root then passes all the tests.
